# Generated by Django 4.2.6 on 2023-10-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('AP', 'Applied'), ('RJ', 'Rejected'), ('NR', 'No Response'), ('IV', 'Interview'), ('OA', 'Online Assessment'), ('AC', 'Accepted'), ('AC', 'Accepted'), ('RR', 'Response Recieved')], max_length=15)),
                ('location', models.CharField(max_length=20)),
                ('onsite', models.BooleanField(default=1)),
                ('referralRecieved', models.BooleanField(default=0)),
            ],
        ),
    ]
